image: openjdk:8-jdk

stages:
- build
- test

build:
  stage: build
  script:
  - ./gradlew assembleDebug
  artifacts:
    paths:
    - app/build/outputs/

unitTests:
  stage: test
  script:
  - ./gradlew test